dist: trusty
sudo: false
language: node_js
node_js: lts/*

install:
  - npm run add-fa-config
  - npm ci

cache:
  directories:
    - $HOME/.npm

script:
  - npm run build-lib && npm run build-docs

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

before_deploy:
  - npm run build-docs

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/ng-components-docs
    on:
      branch: alpha

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
